spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC
    username: root
    password: root


logging:
  level:
    com.learn.blog: debug
  file:
    name: ./log/blog_dev.log
server:
  port: 8079
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
